backend:
  name: github
  repo: dammmien/statik # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "example/assets" # Folder where user uploaded files should go
public_folder: "/assets"

collections: # A list of collections the CMS should be able to edit
  - name: "item" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Item" # Used in the UI, e.g., "New Post"
    folder: "example/content/collections" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Imports", name: "statik_imports", widget: "hidden", default: {import: "content/imports/import.json"}}
      - {label: "URL", name: "statik_output", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", default: "Enter description"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
  - name: "recipes" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Recipes" # Used in the UI, ie.: "New Post"
    folder: "example/content/recipes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "URL", name: "_output", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Preparation", name: "preparation_time", widget: "number"}
      - {label: "Cooking", name: "cooking_time", widget: "number"}
      - {label: "Image", name: "image", widget: "image"}
      - label: "Ingredients"
        name: "ingredients"
        widget: "list"
        fields:
          - label: Quantity
            name: quantity
            widget: number
          - label: "Unit"
            name: "unit"
            widget: "string"
          - label: "Type"
            name: "type"
            widget: "string"
      - label: "Instructions"
        name: "instructions"
        widget: "list"
        fields:
          - label: "Text"
            name: "text"
            widget: "string"
