backend:
  name: github
  repo: dammmien/statik
  branch: master

media_folder: /example/assets/images/uploads
public_folder: /

collections:

  - name: item
    label: Item
    folder: example/content/collections
    create: true
    fields:
      - label: Title
        name: title
        widget: string

      - label: Imports
        name: statik_imports
        widget: hidden
        default:
          - import: content/imports/import.json

      - label: URL
        name: statik_output
        widget: string

      - label: Body
        name: body
        widget: markdown
        default: Enter description

      - label: Featured Image
        name: thumbnail
        widget: image

  - name: recipes
    label: Recipes
    folder: example/content/recipes
    create: true
    fields:
      - label: URL
        name: statik_output
        widget: string

      - label: Title
        name: title
        widget: string

      - label: Preparation
        name: preparation_time
        widget: number

      - label: Cooking
        name: cooking_time
        widget: number

      - label: Image
        name: image
        widget: image

      - label: Ingredients
        name: ingredients
        widget: list
        fields:
          - label: Quantity
            name: quantity
            widget: number
          - label: Unit
            name: unit
            widget: string
          - label: Type
            name: type
            widget: string

      - label: Instructions
        name: instructions
        widget: list
        fields:
        - label: Text
          name: text
          widget: text
