backend:
  name: github
  repo: dammmien/statik
  branch: master

media_folder: /example/assets/images/uploads
public_folder: /

collections:

  - name: recipes
    label: Recipes
    folder: example/content/recipes
    extension: "json"
    create: true
    fields:
      - label: URL
        name: _output
        widget: string

      - label: Title
        name: title
        widget: string

      - label: Preparation
        name: preparation_time
        widget: number

      - label: Cooking
        name: cooking_time
        widget: number

      - label: Image
        name: image
        widget: image

      - label: Ingredients
        name: ingredients
        widget: list
        fields:
          - label: Type
            name: type
            widget: string

          - label: Quantity
            name: quantity
            widget: string

      - label: Instructions
        name: instructions
        widget: list
        fields:
          - label: Text
            name: text
            widget: string

